import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import LogoutButton from "./logout-button";

const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "500",
    "700",
    "800",
    "900",
  ],
});

export const metadata: Metadata = {
  title: "Auth.js Demo Project",
  description: "Generated by kerry Li",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <div>
          {session?.user?.email ? (
            <div>
              {session.user.email}
              <LogoutButton />
            </div>
          ) : (
            "No currectly logged in user"
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
